### ISSUE TITLE
Github Issue Template - Blog Post Proposal

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#105]
```[tasklist]
### Tasks
- [x] Proposal for Publication (EN) - https://github.com/sveltevietnam/sveltevietnam.dev/commit/5efaa4b9e0660f0a9dae95806978e11719b59508
- [x] Proposal for Publication (VI) - https://github.com/sveltevietnam/sveltevietnam.dev/commit/76a8f9c19053e59efac98892b89dc0c155fa27fe
- [x] Request to Link (EN) - https://github.com/sveltevietnam/sveltevietnam.dev/commit/4d6acd0f239bec76eeacccf934587b1b443d9d99
- [x] Request to Link (VI) - https://github.com/sveltevietnam/sveltevietnam.dev/commit/061c6e0d9cf9ef43319bd7b3cc0ef7105dff14c9
```

**Comment by vnphanquang** [comment]
Done as noted in description
