### ISSUE TITLE
Home Page Design Update

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#110]
## Context

Home page design has recently been updated by Trong. We will reflect the changes to the source code here.
```[tasklist]
### Tasks
- [x] Apply new typography system
- [x] Remove figures at Community section?
- [x] Update design of project card
- [x] Add navigation buttons to Projects section
- [x] Update header background and figures
```
