### ISSUE TITLE
Consider Domain Transfer to Cloudflare

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#119]
## Context

As [Google Domain will be moved into Squarespace](https://support.google.com/domains/answer/13689670?hl=en), we should move `sveltevietnam.dev` to Cloudflare to avoid the complexity of another platform (we are already using Cloudflare as our DNS)

Things to keep track

```[tasklist]
### Tasks
- [x] Transfer `sveltevietnam.dev` from Google Domains to Cloudflare. See https://developers.cloudflare.com/registrar/get-started/transfer-domain-to-cloudflare
- [x] Forward email back to Google. See [Cloudflare: Activate Gmail for Google Workspace](https://support.google.com/a/answer/7174013?hl=en#zippy=%2Cthe-setup-tool-wants-me-to-add-another-mx-record)
- [x] Keep Google Workspace subscription intact
- [x] Preferably, keep WHOIS privacy enabled after transfer. Check [here for WHOIS](https://www.whois.com/whois/sveltevietnam.dev)
```
