### ISSUE TITLE
Roadmap Page

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#126]
## Context

We need a `/roadmap` page to better communicate what is being worked on and what is expected. We will need this pre initial release.

#### Objective

> [!IMPORTANT]
> Bootstrap the project and set up all necessary pieces that together establish a reasonable development process.

#### Major Tasks

- [ ] a Roadmap page
- [x] Basic metadata and SEO setup, including `sitemap.xml`, Google Search Console, Google Analytics (via `gtag` and `partytown`)
- [x] Setup Discord websocket service and bot to enrich experiences of community members both in discord server and on the official sveltevietnam.dev site.
- [x] Introduce a complete home page with initial design
- [x] Design and integrate an official Svelte Vietnam logo, publish [Branding Guidelines](https://github.com/sveltevietnam/branding)
- [x] Introduce [Project Reference](https://github.com/sveltevietnam/sveltevietnam.dev/blob/main/docs/PROJECT_REFERENCES.md)
- [x] Setup Github organization and projects.
---

#### Objective

> [!IMPORTANT]
> Prepare for the first public release of `sveltevietnam.dev`

#### Major Tasks

- [ ] Design `Svelte Vietnam Community Survey 2023`
- [ ] Introduce a complete `/blog` page with initial design
- [ ] Schedule the first event: <name_here> (virtual meetup stream, via Discord?) 
- [ ] Introduce a complete `/events` page with initial design

#### Additional Release Items

- [ ] First blog post: "Community: from Local to Global"
---

#### Connecting Tasks

- [ ] Submit an Open Collective for Svelte Vietnam
- [ ] Introduce a complete `/sponsor` page with initial design

#### Objective

> [!IMPORTANT]
> A job board for svelte & frontend related jobs. Companies instead of going through agencies or headhunters to find talents can sponsor Svelte Vietnam and post to the /jobs page.

#### Major Tasks

- [ ] Implement a basic web scraper cron job for Svelte-related jobs.
- [ ] Introduce a process for sponsors to post jobs
- [ ] Introduce a complete `/jobs` page with initial design

```[tasklist]
### Tasks
- [x] Design a miniimal `/roadmap` page
- [x] Add i18n-aware content based on issue description
- [x] Add entry to footer
- [x] Add entry to sitemap.xml
```
