### ISSUE TITLE
Set up @services/mailer | Subscription Logics Migration

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#130]
## Context

Following #123, we need to have a dedicated service for management mails (subscription & sending emails)

```[tasklist]
### Tasks
- [x] Setup `@services/mailer` as a svelte-kit project using cloudflare page adapter
- [x] Setup authentication between internal services (called "Inter-service Communication") with HMAC signing
- [x] Setup `@internals/isc` for encapsulating http Data Transfer Object (DTO) types and helpers
- [x] Transfer the subscription logics from `mail.server.ts` in `@sites/www` to `/subcribe` endpoint
- [ ] Setup `deploy_mailer.yaml` github workflow based on existing `deploy_www.yaml`
- [ ] Deploy `@services/mailer` to `mailer-sveltevietnam` cloudflare page project
- [x] Setup DNS to route `mailer.sveltevietnam.dev` to cloudflare page above
- [x] Switch D1 binding database to `mailer`, rename to `sv_mailer_preview` & `sv_mailer_production`
- [ ] Sync migrations towards remote D1 databases
```

## Later Considerations

Enable Access Policy in Cloudflare for `mailer` (perhaps `mailer.sveltevietnam.dev/admin`)
