### ISSUE TITLE
Mailer Service `/send` API

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#134]
## Context

Following #122, `mailer` service has been setup, we will need to integrate `MJML` and the `/send` API to send emails

```[tasklist]
### Tasks
- [x] Set up MJML workflow for developing email template, including build step & lint-staged script
- [x] Set up the `/send` API with `mailchannels`, allows specifying in request body the email template and injected variables
- [x] Support i18n (`en` & `vi`)
- [x] dynamic GET `/mail/[token]` for viewing mail as a web page (where token is a jsonwebtoken)
- [x] design & implement an email template for "subscription sucess
- [x] Send email as success notification after user registers for notification in `event` or `job` pages.
- [x] add `JWT_SECRET` to environments & load in `deploy_mailler.yaml` workflow config
- [x] strategy for subscription management (let user select / deselect what domain to receive emails)
- [ ] deploy to production
```

## Later Considerations

Add `hygen` script to generate new error (isc) / new template
