### ISSUE TITLE
Add a `/design/blog` page that lists all the common components and strategy used in writing blog posts

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#188]
## Context

There have been a couple of published blog posts. Patterns and some common components have emerged. We probably need a place to list all of them, making it easier to maintain and for writers to refer to

```[tasklist]
### Tasks
- [x] Add `design/blog` pages
- [x] Mention that the default style is already handle by `prose` of `tailwindcss/typography`
- [x] Add block links in `/design` page to `/colors`, /typography`, and `/blog`
- [x] Add reference for code block, the languages supported, and how to add more language if necessary
- [x] Add reference for `c-callout`
```
