### ISSUE TITLE
Site Settings Menu

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#214]
## Context

We need a UI for user settings to create the best experience.This settings should include options for:

- Theme
- Language
- Reduce Motion (depends on #68)
- Splash Screen

## Where to Store

```[tasklist]
### Tasks
- [x] Each settings item in settings is stored as a separate cookies and navigate immediately if necessary
- [x] Load above into a global Svelte context
```

## The Entry

```[tasklist]
### Tasks
- [x] Icon button at header
- [x] Without Javascript, open the `/settings` page
- [x] With JS, open a modal with same content as in `/settings` (saving user a round-trip to another page and back)
```

## The `/settings` Page and UI

```[tasklist]
### Tasks
- [x] Create a dedicated page `/settings` with HTML form for configuration
- [x] Make `/settings` work even without Javascript
- [x] Extract the core UI into a component to reuse in modal (see [The Entry](#the-entry))
```
