### ISSUE TITLE
Consideration of Deployment Platforms?

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#60]
## Context

We are using vercel. But are there better alternatives?

- [railway]
- [render]
- [cloudflare]: most promising, focus on security, more affordable than vercel. Has captcha alternative ([turnstile](https://www.cloudflare.com/products/turnstile/]), which will help with https://github.com/sveltevietnam/sveltevietnam.dev/issues/44.

Let's migrate to [cloudflare]!

## Todos

- [x] config deployment for `cloudflare`
- [ ] alternative for `x-vercel-ip-country` header to detect user location
- [ ] remove vercel artifacts and references and replace with cloudflare where applicable

[cloudflare]: https://www.cloudflare.com/en-gb/
[railway]: https://railway.app/
[render]: https://render.com
