### ISSUE TITLE
Subscribe to Discord New Member Event

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#72]
## Context

To provide a richer UX & prompt user to join discord, let's subscribe to [Discord Gateway](https://discord.com/developers/docs/topics/gateway) and display a push notification / toast whenever a new member joins the server

## Considerations & Findings

Discord currently provides 2 APIs to interact with servers (called "guilds" in its developer reference):

- [Webhook](https://discord.com/developers/docs/resources/webhook), using REST
- [Gateway](https://discord.com/developers/docs/topics/gateway), using websocket

To achieve the objective of this issue, we have to use the Gateway API, as webhooks do not allow subscription to guild & message events. 

I want to utilize cloudflare architecture as much as possible. However, there are 2 problems:

1. [Discord blocks gateway connection requests from cloudflare workers](https://community.cloudflare.com/t/discord-reports-that-they-intentionally-block-cf-workers/509408)
2. The most convenient wrapper in JS land to interact with discord currently available is [discord.js]. However, it requires NodeJS environment, which [cloudflare does not have full support for](https://github.com/discordjs/discord.js/discussions/8428).

Due to these limitations, let's switch gears and create a [fastify] based server for this task. Things to consider:

- where to deploy to? Best option right now seems to be [render]?
- which domain / host to deploy to? Perhaps `discord.sveltevietnam.dev` seems to be good?

Essentially we have ended up building a discord bot here. But maybe it's a good opportunity and setup for further work...

## Guiding Strategy

1. keep things as minimal as possible
2. put necessary & minimal security layer to avoid abuse of api
3. use vanilla Javascript with JSDocs and `jsconfig` as an experiment to see how the 'vanilla world' has matured 

## Todo

- [x] create a `@services/discord` project in this monorepo
- [x] setup [fastify] for server, use necessary middleware & plugin for env, security, and websocket
- [x] redirect `/` to the discord invite link
- [x] use `/websocket` for connection `sveltevietnam.dev`
- [x] use [discord.js] and setup necessary discord bot / application to connect to gateway and listen for new guild member event
- [ ] try deploying to [render]?
- [ ] publish this server to `discord.sveltevietnam.dev` (follow [cloudflare DNS & render guide](https://render.com/docs/configure-cloudflare-dns)?)

## Improvement

- [x] use [zod] and a custom fastify plugin for better env loading
- [x] extract discord related logics into custom class / file

## Next steps

- [ ] expand on this existing work and send a bot welcome message to the `hello` channel each time a new member joins
- [ ] think about also subscribing to the guild message event since that will be more frequent (and not too much at the moment), which will help bring a sense of activity on the `sveltevietnam.dev` site.
- [ ] setup a toast / push notification system on the client side to receive & display the above subscribed events.

[zod]: https://zod.dev/
[render]: https://render.com/
[fastify]: https://www.fastify.io/
[cloudflare wrangler]: https://developers.cloudflare.com/workers/wrangler/
[cloudflare worker]: https://developers.cloudflare.com/workers/
[cloudflare websocket]: https://developers.cloudflare.com/workers/learning/using-websockets/#writing-a-websocket-client
[discord.js]: https://discord.js.org/
