### ISSUE TITLE
SEO Setup

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#80]
## Todos

- [x] All necessary assets to complete `app.html` link & meta tags
    - [x] favicons (https://github.com/sveltevietnam/sveltevietnam.dev/issues/23)
    - [x] site.webmanifest (https://github.com/sveltevietnam/sveltevietnam.dev/issues/23)
    - [x] screenshots
- [x] setup canonical link for each page (preview. domain should have same canonical as production) https://github.com/sveltevietnam/sveltevietnam.dev/commit/db89437aa0b8a6ceff0068304aa57175ca1f94e0
- [x] meta tags for each pages (based on what is defined in [app.d.ts](https://github.com/sveltevietnam/sveltevietnam.dev/blob/2da2b6fd0c28ce4b15a6250d47642bc0aad135a5/sites/www/src/app.d.ts)) https://github.com/sveltevietnam/sveltevietnam.dev/commit/db89437aa0b8a6ceff0068304aa57175ca1f94e0
- [ ] OG image for each page (do later in https://github.com/sveltevietnam/sveltevietnam.dev/issues/85)
