### ISSUE TITLE
Dedicated Open Graph Images

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#85]
## Context

For best SEO and social media sharing, each page should have a dedicated image just for this purpose. This is the `og:image` in Open Graph protocol. Please design the OG images for each page with the following specs:

- represent the page with minimal details,
- in light mode
- aspect ratio 1200:630
- 2 variants for EN & VI

Ref: https://developers.facebook.com/docs/sharing/webmasters/images/
```[tasklist]
### Tasks
- [x] Fallback OG image
- [x] Dedicated OG image for home page
- [x] Dedicated OG image for events page
- [x] Dedicated OG image for blog page
- [x] Dedicated OG image for roadmap page
- [x] Dedicated OG image for coc page
```

**Comment by vnphanquang** [comment]
Done via https://github.com/sveltevietnam/sveltevietnam.dev/commit/7a2d2c8be69656a70eac36d4f4cd4843f4369e34
