### ISSUE TITLE
Refactor to Set Color Scheme Cookie Client Side

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#87]
## Context

The color scheme cookie, used for self-explanatory reason, has been set from server in a HTTPOnly manner. This is a bit cumbersome as it requires:

- an `/api/color-scheme` POST request, and
- invalidation of a load dependency.

As we have to switch the theme (`document[data-color-scheme]`) on client side any way to immediately update the css, let's refactor to set this cookie using the `document.cookie` API, which should keep code more minimal and save resources.

## Todo

- [x] Update `.env` for the cookie env name to be able to use on client side
- [x] change settings in cloudflare to reflect the above env name change
- [x] use `document.cookie` on theme switch
- [x] change cookie options in `hooks.server` and remove `HttpOnly`
- [x] remove load dependency invalidation code

## Resources

- https://scriptraccoon.dev/blog/darkmode-toggle-sveltekit
- https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
