### ISSUE TITLE
Consider `$app/environment.version` as Alternative to BUILD_* global variable

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#89]
## Context

Currently, we are versioning the site using constant replacement with [vite define](https://vitejs.dev/config/shared-options.html#define), [seen in vite.config.ts](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/vite.config.ts#L34-L36). 

![Image](https://user-images.githubusercontent.com/25895844/249647046-514c3b7a-d87e-48b9-bcdb-3327a782d462.png)

This is working well but a bit verbose, there are a couple of extra setup needed for [typescript](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/src/app.d.ts#L14-L16) and [eslint](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/.eslintrc.cjs#L27-L29) to stop screaming.

Meanwhile, sveltekit exposes [config.version](https://kit.svelte.dev/docs/configuration#version), available at runtime through `$app/environment.version`. So perhaps we should explore the possibility to switch to this for site versioning, which will also provide more benefits in the future should we run into problems described in the sveltekit docs.

## Todo

- [x] Use similar setup in [current vite.config.ts](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/vite.config.ts#L34-L36) for `config.version.name` in `svelte.config.js`
- [x] Considering concat the `package.json` version as well. And change it to `prelease` if possible
- [x] Remove [typescript](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/src/app.d.ts#L14-L16) and [eslint](https://github.com/sveltevietnam/sveltevietnam.dev/blob/e2a64146cec6f90a6ebef14279a960bfbf7f25d4/sites/www/.eslintrc.cjs#L27-L29) setup
